add introduction notebook for jax
Haleshot/marimo-tutorials pull request #35
Opened 2024-10-29 07:02 UTC by metaboulie

## 📝 Summary

## 🔍 Description of Changes

## 📋 Checklist

- [ ] I have read the [contributor guidelines](../CONTRIBUTING.md).
- [ ] For large changes, or changes that affect the public API: this change was discussed or approved through an issue, on [Discord](https://discord.gg/JE7nhX6mD8), or the community [discussions](https://github.com/marimo-team/marimo/discussions) (Please provide a link if applicable).
- [ ] I have added tests for the changes made.
- [ ] I have run the code and verified that it works as expected.

## 📜 Reviewers

@Haleshot OR @metaboulie

2024-10-29 07:03 UTC, metaboulie commented
@Haleshot  have a look when you are free :)

2024-10-29 07:04 UTC, Haleshot commented
> @Haleshot have a look when you are free :)

Will do!

2024-10-29 16:09 UTC, Haleshot requested changes
The notebook gives great insights on Jax (atleast for a beginner like me!). Do let me know if you need in working on the suggestions offered in the review (following the [`init.py`](https://github.com/Haleshot/marimo-tutorials/blob/main/init.py)).

2024-10-29 16:09 UTC, Haleshot commented on marimo-tutorials/Data-Science/Jax/introduction.py
> +    ).callout(kind="info")
Really like this callout!

2024-10-29 16:27 UTC, Haleshot reviewed
Also, can we change the name of the notebook | location of the notebook to somewhere better? Since JAX is along the lines of PyTorch, Tensorflow, it can belong somewhere in [`marimo-tutorials\artificial-intelligence\deep-learning`](https://github.com/Haleshot/marimo-tutorials/tree/main/marimo-tutorials/artificial-intelligence/deep-learning)? What do you think?

2024-10-30 01:03 UTC, metaboulie commented on marimo-tutorials/Data-Science/Jax/introduction.py
> +    mo.md(r"""# An Introduction to Jax""")
yeah, I realized that I forgot to add the header

2024-10-30 01:06 UTC, metaboulie commented
Thanks for the review
To sum up, I will add more hyperlinks, the header, and move it to `marimo-tutorials\attificial-intelligence\deep-learning\jax`

2024-10-30 01:41 UTC, merged